# Generated by Django 4.2.6 on 2023-11-13 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("plantTypes", models.CharField(blank=True, max_length=500, null=True)),
                ("area", models.IntegerField(blank=True, null=True)),
                ("plantPlanned", models.IntegerField(blank=True, null=True)),
                ("donation", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to=projects.models.document_upload
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to=projects.models.image_upload
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
