# Generated by Django 4.2.6 on 2023-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectinfo",
            old_name="plantPlanned",
            new_name="plant_planned",
        ),
        migrations.RenameField(
            model_name="projectinfo",
            old_name="plantTypes",
            new_name="plant_types",
        ),
        migrations.AddField(
            model_name="projectinfo",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectinfo",
            name="plants_planted",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
