# Generated by Django 4.2.6 on 2023-11-21 08:28

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_plantplanned_projectinfo_plant_planned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(upload_to=projects.models.plant_image_upload),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectinfo",
                    ),
                ),
            ],
        ),
    ]
