# Generated by Django 4.2.6 on 2023-11-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectinfo_plant_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectinfo",
            name="plant_image",
        ),
    ]
