# Generated by Django 4.2.6 on 2023-11-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_projectinfo_plant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plant_images",
                to="projects.projectinfo",
            ),
        ),
    ]
