# Generated by Django 4.2.3 on 2023-11-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_plantimage_project"),
        ("projects", "0006_transaction_projectreport"),
    ]

    operations = []
