# Generated by Django 4.2.6 on 2023-11-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("General Inquiry", "General Inquiry"),
                            ("Support", "Support"),
                            ("Sales", "Sales"),
                        ],
                        default="General Inquiry",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
