# Generated by Django 4.2.6 on 2023-11-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_delete_approver"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Issuer",
        ),
    ]
